### PR TITLE
Reorganized into multi-module maven project

### PR DESCRIPTION
**Pull request by dogeared**
This PR reorganizes the library and examples into a mulit-module maven project.

It builds a "fat" jar that includes all dependencies so that it can be used standalone.

It also sets the stage to be able to publish the blink1 java library to maven central.

There are some minor code updates and bug fixes as well.

### CODE REVIEW

**Comment by bdemers** [comment]
This is a great update!  (and I can confirm this is a pretty standard way of doing this)

**Comment by dogeared** [comment]
I wasn't too familiar with the processing stuff. I didn't change that folder. Maybe we could do a quick zoom sync on that to see if there's anything that needs updating there?

**Comment by dogeared** [comment]
@todbot - I did a second pass at reorganizing and the Processing.org examples all work AND, when you build the project, it automatically sets up the `~/Documents/Processing/libraries` with the blink1 library. I updated the README in the `blink1-processing-examples` folder too.

**Comment by dogeared** [comment]
@todbot Thanks! I'd like to get the library listed on maven central. Then, people can just include the library as a dependency in their project without having to build the fat-jar. Would you be ok if I got the ball rolling on that? Also: would you mind setting a topic for the blink1-java repo of: `hacktoberfest`? This way the PR will count toward it ;)

**Pull request merged**
